name: dart-macd-stoch-bot

on:
  schedule:
    # 매일 09:05 KST (= 00:05 UTC)에 실행
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    concurrency:
      group: dart-bot
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          DART_API_KEY:       ${{ secrets.DART_API_KEY }}
          SCALE_MACD:         true
          SAVE_CSV:           false
          # 필요시 Git LFS/폰트 파일을 사용한다면 FONT_PATH 지정
        run: |
          python main.py
